### ISSUE TITLE
No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by temuller** [pypeit/PypeIt-development-suite#221]
I installed pypeit in an anaconda environment using `pip` and `python 3.9`. I am running the tests to make sure it is working correctly, but when I run `./pypeit_test pypeit_tests`, I get this error: `No module named 'numpy.core._multiarray_umath'`. 

Full output: [test_report.txt](https://drive.google.com/file/d/17Eycngo72xL4sgpOIKi4ZdlEA1abTEMj/view?usp=sharing)

**Comment by profxj** [comment]
What part of the documentation inspired you to execute that test command?

**Comment by profxj** [comment]
Sorry, I see it now.

Thoughts @badpandabear ?

**Comment by badpandabear** [comment]
This is strange, I've never seen that error before. It states that the Python version is 3.10 but conda is clearly running in a Python 3.9 environment.  I tried a quick test but couldn't reproduce it. 
@temuller Could you provide additional information? Such as what OS and OS version you're running on? Are you running PypeIt from git and if so what branch? What was the exact pip command you used to install pypeit?

**Comment by temuller** [comment]
I used `pip install "pypeit[pyqt5]"` on Ubuntu 22.04.

**Comment by badpandabear** [comment]
I managed to reproduce the issue. I did so by installing a version of pytest *outside* of the conda environment, activating the conda environment, and then running pypeit_test. This caused it to use a version of pytest from Ubuntu 22.04's default version of python (3.10), which didn't work in the conda environment with a 3.9 version of python. So I suspect you had installed pytest at some point in the past and pypeit_test is trying to use it.

If this is what's happening to you, it's a missing step in the dev-suite documentation.  You should be able to fix this by running the following with the conda environment activated:

`pip install "pypeit[test]"`

and then logging out and back in so that bash picks up the new path for pytest. This will install the additional test packages the dev suite uses, including pytest.  

Note: if the Python 3.10 version of pytest is in the PATH environment earlier than the conda version, this problem will still happen. You'll then have to edit your .bashrc to make sure the conda path comes first. But that seems unlikely since conda sticks itself in front of the PATH.

**Comment by kbwestfall** [comment]
@temuller Your issue when running pypeit (https://github.com/pypeit/PypeIt/issues/1468) may be related to @badpandabear 's sleuthing here.

**Comment by temuller** [comment]
I believe you are right, python was using `pytest` from outside the environment. I did a clean installation on a new anaconda environment and seems to be working now. I used:
```
pip install "pypeit[pyqt5,bottleneck,test]"
```
I get like 4 errors, but I believe those are all related to missing files as I did not download the complete `RAW_DATA` directory.

Thanks!
